name = "flow-idem-ingest"
main = "workerd-tests/build/index.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["durable_object_alarms"]

kv_namespaces = [
  { binding = "EVENTS_KV", id = "6d92b88ccab948e99a385c5e80b7c8af", preview_id = "19d23c0023be4a0f8375f9e522d6b144" }
]

[[durable_objects.bindings]]
name = "DEDUP_DO"
class_name = "FlowDurableObject"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["FlowDurableObject"]

[vars]
OTEL_EXPORTER_OTLP_ENDPOINT = "https://otel.example.com/v1/traces"
